const productos = [
    {
        id: 1,
        productName: "Blusa",
        price: 25,
        quanty: 1,
        img: "media/ryzen 7 5700g",
    },
    {
        id: 2,
        productName: "Vestido",
        price: 45,
        quanty: 1,
        img: "media/vestido.png",
    },
    {
        id: 3,
        productName: "Jeans",
        price: 50,
        quanty: 1,
        img: "media/jeans.png",
    },
    {
        id: 4,
        productName: "Vestido de verano",
        price: 40,
        quanty: 1,
        img: "media/sundress.jpg",
    },
    {
        id: 5,
        productName: "Camiseta",
        price: 20,
        quanty: 1,
        img: "media/tshirt.jpg",
    },
    {
        id: 6,
        productName: "Suéter",
        price: 55,
        quanty: 1,
        img: "media/sweater.png",
    },
    {
        id: 7,
        productName: "Falda",
        price: 35,
        quanty: 1,
        img: "media/skirt.png",
    },
    {
        id: 8,
        productName: "Chaqueta",
        price: 70,
        quanty: 1,
        img: "media/jacket.png",
    },
    // {
    //     id: 9,
    //     productName: "Pantalones cortos",
    //     price: 30,
    //     quanty: 1,
    //     img: "media/shorts.png",
    // },
    // {
    //     id: 10,
    //     productName: "Sudadera con capucha",
    //     price: 60,
    //     quanty: 1,
    //     img: "media/hoodie.png",
    // },
    // {
    //     id: 11,
    //     productName: "Cárdigan",
    //     price: 65,
    //     quanty: 1,
    //     img: "media/cardigan.png",
    // },
];
