const products = [
    {
        id: 1,
        productName: "Samsung",
        price: 25,
        quanty: 1,
        img: "/media/img/net01-.jpeg",
        stars: 5,
    },
    {
        id: 2,
        productName: "Lenovo",
        price: 45,
        quanty: 1,
        img: "/media/img/net-02.jpg",
        stars: 4.5,
    },
    {
        id: 3,
        productName:"DELL",
        price: 50,
        quanty: 1,
        img: "/media/img/aur-01.jpg",
        stars:3,
    },
    {
        id: 4,
        productName: "Samsung",
        price: 40,
        quanty: 1,
        img: "/media/img/celu1.jpeg",
        stars: 4.5
    },
    {
        id: 5,
        productName: "Samsung",
        price: 20,
        quanty: 1,
        img: "/media/img/celu4.jpeg",
        stars:2.5
    },
    {
        id: 6,
        productName: "Samsung",
        price: 55,
        quanty: 1,
        img:"/media/img/celu5.jpeg",
        stars:5,
    },
    {
        id: 7,
        productName: "Sansung",
        price: 35,
        quanty: 1,
        img: "/media/img/celu6.jpeg",
        stars:4,
    },
    {
        id: 8,
        productName: "Samsung",
        price: 70,
        quanty: 1,
        img: "/media/img/celu7.jpeg",
        stars:5
    },
    {
        id: 9,
        productName: "Samsung",
        price: 70,
        quanty: 1,
        img:"/media/img/celu8.jpeg",
        stars:4.5,
    },
    {
        id: 10,
        productName: "Ps5",
        price: 70,
        quanty: 1,
        img:"/media/img/Ps5.png",
        stars:5,
    },
    {
        id: 11,
        productName: "Sony",
        price: 70,
        quanty: 1,
        img:"/media/img/aur-02.jpg",
        stars:3,
    },
    {
        id: 12,
        productName: "Samsung",
        price: 70,
        quanty: 1,
        img:"/media/img/aur-03.png",
        stars:3.5,
    },

];
